@startuml DiceManager

skinparam classAttributeIconSize 0
skinparam classFontStyle bold
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 30

title Diagram Kelas DiceManager

class DiceManager {
    - die1 : int
    - die2 : int
    __
    + DiceManager()
    + rollRandom() : pair<int, int>
    + setManual(d1 : int, d2 : int) : void
    + getDie1() : int
    + getDie2() : int
    + getTotal() : int
    + isDouble() : bool
}

@enduml
