@startuml Overview
title View

skinparam classAttributeIconSize 0
skinparam classFontSize 13
skinparam classFontStyle Bold
skinparam classAttributeFontSize 12

skinparam groupInheritance 2

class View {
  #x : int
  #y : int
  #scale : float
  #visible : bool
  #interactable : bool
  #renderFunc : auto
  --
  +getX() : int
  +getY() : int
  +getScale() : float
  +isVisible() : bool
  +isInteractable() : bool
  +movePosition(x : int, y : int) : void
  +movePositionDelta(dx : int, dy : int) : void
  +setScale(scale : float) : void
  +setVisibility(visible : bool) : void
  +setRender(render : auto) : void
  +render() : void
}

class Interactable {
  #boundingBox : int[4]
  #active : bool
  #draggable : bool
  #gameCommand : CommandProcessor*
  #onHoverFunc : auto
  #onClickedFunc : auto
  --
  + isActive() : bool
  + isDraggable() : bool
  + isInBoundingBox(x : int, y : int) : bool
  + getGameCommand() : CommandProcessor*
  + getBoundingBox() : int[4]
  + setActive(active : bool) : void
  + setDraggable(draggable : bool) : void
  + setGameCommand() : void
  + setOnHover(onClicked : auto) : void
  + setOnClicked(onClicked : auto) : void
  + moveOnDragged() : void
  + onHover() : void
  + onClicked() : void
}

class Entry {
  -defaultText : string
  -entryText : string
  -onEnterFunc : auto
  --
  + isActive() : bool
  + getEntryText() : string
  + setDefaultText(default : string) : void
  + setEntryText(text : string) : void
  + setOnEnter(onEnter : auto) : void
  + onEnter() : void
}

abstract Popup {
}

class IndefinitePopup {
  #exitButton : Interactable
}

class TimedPopup {
  #popupDuration : int
}

class TilePopupView {
  -player : Player&
  -tile : Tile&
  --
  + renderTilePopupBase() : void()
  + render() : void()
}

class TaxTilePopupView {
  -taxTile : TaxTile&
  --
  + render() : void()
}

class GoTilePopupView {
  -goTile : GoTile&
  --
  + render() : void()
}

class ExceptionPopupView {
  -exceptionType : GameException&
  --
  +render() : void
}

class BoardView {
  -board : Board&
  -tileViews : vector<TileView&>
  --
  + render() : void
}

abstract TileView {
  #tile : Tile&
  #tileType : string
  #tileImagePath : string
  --
  # renderTileBase() : void
}

class MoneyTileView {
  -moneyAmount : int
  --
  + render() : void
}

class PropertyTileView {
  -property : Property&
  --
  # renderPropertyTileBase() : void
  + render () : void
  + onHover() : void
  + onClicked() : void
}

class StreetTileView {
  -street : StreetProperty&
  --
  + render() : void
}

abstract PropertyActView {
  #property : Property&
  #inInventory : bool
  #mortgageButton : Interactable
  --
  + onHover() : void
  # renderActBase() : void
}

class StreetActView {
  -street : StreetProperty&
  -buyHouseButton : Interactable
  --
  + render() : void
}

class RailroadActView {
  -railroad : RailroadProperty&
  --
  + render() : void
}

class UtilityActView {
  -Utility : UtilityProperty&
  --
  + render() : void
}

class CardDeckView<T> {
  -cardDeck : CardDeck<T>
  --
  + render() : 
  + onHover() : void
  + onClicked() : void
}

class CardView {
  -card : Card&
  -cardBGImgPath : string
  -flipped : bool
  --
  + render() : void
  + onHover() : void
  + onClicked() : void
}

class SkillCardView {
  -skillCard : SkillCard&
  --
  + onHover() : void
  + onClicked() : void
}

class DiceView {
  -dice : DiceManager&
  --
  + render() : void
  + onHover() : void
  + onClicked() : void
}

class PlayerProfileView {
  -player : Player*
  -profileImgPath : string
  --
  + render() : void
  + onHover() : void
  + onClicked() : void
  + setProfileImg(imgPath : string) : void
}

class PlayerPieceView {
  -player : Player&
  --
  + render() : void
}

class PlayerInventoryView {
  -player : Player&
  -properties : vector<PropertyActView>
  -skillCards : vector<SkillCardView>
  --
  + render() : void
}

abstract MenuView {
}

class AuctionMenuView {
  -auction : auctionManager&
  -auctionedProperty : PropertyActView
  -playerProfiles : vector<PlayerProfileView>
  -bidButton : Interactable
  --
  + render() : void
}

class MainMenuView {
  -startButton : Interactable
  -loadFileEntry : Entry
  -exitButton : Interactable
  --
  + render() : void
}

class GameFinishMenuView {
  -playAgainButton : Interactable
  -returnToMainMenuButton : Interactable
  --
  + render() : void
}

class PauseView {
  -saveGameButton : Interactable
  -returnToMainMenuButton : Interactable
  --
  + render() : void
}

class TransactionLogView {
  -log : TransactionLogger
  --
  + render() : void
}

class SavePopupView {
  -saveFileEntry : Entry
  -saveButton : Interactable
  --
  + render() : void
}

class BankruptcyView {
  -bankruptPlayer : Player&
  --
  + render() : void
}

class FestivalStartView {
  -player : Player&
  --
  + render() : void
}

class FestivalPropertyView {
  -street : StreetProperty&
  --
  + render() : void
}

class JailPopupView {
  --
  + render() : void
}

class FreeParkingPopupView {
  -amountGotten : int
  -freeParkingEmpty : bool
  --
  + render() : void
}

View <|-- Interactable
View <|-- BoardView
View <|-- TileView
View <|-- PlayerPieceView
View <|-- Popup
View <|-- MenuView
MenuView <|-- MainMenuView
MenuView <|-- AuctionMenuView
MenuView <|-- GameFinishMenuView

Interactable <|-- CardDeckView
Interactable <|-- CardView
Interactable <|-- DiceView
Interactable <|-- PlayerProfileView
Interactable <|-- PropertyTileView
Interactable <|-- PropertyActView
Interactable <|-- Entry

Popup <|-- IndefinitePopup
Popup <|-- TimedPopup

IndefinitePopup <|-- PlayerInventoryView
IndefinitePopup <|-- PropertyActView
IndefinitePopup <|-- SavePopupView
IndefinitePopup <|-- TransactionLogView
IndefinitePopup <|-- PauseView
IndefinitePopup <|-- ExceptionPopupView
IndefinitePopup <|-- BankruptcyView
IndefinitePopup <|-- FestivalStartView

TimedPopup <|-- TilePopupView
TimedPopup <|-- FestivalPropertyView

TilePopupView <|-- GoTilePopupView
TilePopupView <|-- TaxTilePopupView
TilePopupView <|-- JailPopupView
TilePopupView <|-- FreeParkingPopupView

TileView <|-- PropertyTileView
TileView <|-- MoneyTileView

PropertyTileView <|-- StreetTileView

CardView <|-- SkillCardView

PropertyActView <|-- StreetActView
PropertyActView <|-- UtilityActView
PropertyActView <|-- RailroadActView

PlayerInventoryView "1" o-- "0..*" PropertyActView
PlayerInventoryView "1" o-- "0..3" SkillCardView

